using System.Diagnostics.CodeAnalysis;

namespace LBPUnion.ProjectLighthouse.Levels;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
// I would remove the LABEL prefix, but some of the tags start with numbers and won't compile
public enum LevelLabels
{
    // Start LBP2 Labels
    LABEL_SinglePlayer,
    LABEL_Multiplayer,
    LABEL_Quick,
    LABEL_Long,
    LABEL_Challenging,
    LABEL_Easy,
    LABEL_Scary,
    LABEL_Funny,
    LABEL_Artistic,
    LABEL_Musical,
    LABEL_Intricate,
    LABEL_Cinematic,
    LABEL_Competitive,
    LABEL_Fighter,
    LABEL_Gallery,
    LABEL_Puzzle,
    LABEL_Platform,
    LABEL_Race,
    LABEL_Shooter,
    LABEL_Sports,
    LABEL_Story,
    LABEL_Strategy,
    LABEL_SurvivalChallenge,
    LABEL_Tutorial,
    LABEL_Retro,
    LABEL_Collectables,
    LABEL_DirectControl,
    LABEL_Explosives,
    LABEL_Glitch,
    LABEL_GrapplingHook,
    LABEL_JumpPads,
    LABEL_MagicBag,
    LABEL_LowGravity,
    LABEL_Paintinator,
    LABEL_PowerGlove,
    LABEL_Sackbots,
    LABEL_Vehicles,
    LABEL_Water,
    LABEL_Brain_Crane,
    LABEL_Movinator,
    LABEL_Paint,
    LABEL_ATTRACT_GEL,
    LABEL_ATTRACT_TWEAK,
    LABEL_HEROCAPE,
    LABEL_MEMORISER,
    LABEL_WALLJUMP,
    // Start LBP Vita Labels
    LABEL_Arcade,
    LABEL_Co_op,
    LABEL_Precision,
    LABEL_Controlinator,
    LABEL_Flick,
    LABEL_Memoriser,
    LABEL_MultiLevel,
    LABEL_Portrait,
    LABEL_RearTouch,
    LABEL_SharedScreen,
    LABEL_Swipe,
    LABEL_Tap,
    LABEL_Tilt,
    LABEL_Touch,
    // Start LBP3 Labels
    LABEL_SINGLE_PLAYER,
    LABEL_RPG,
    LABEL_TOP_DOWN,
    LABEL_CO_OP,
    LABEL_1st_Person,
    LABEL_3rd_Person,
    LABEL_Sci_Fi,
    LABEL_Social,
    LABEL_Arcade_Game,
    LABEL_Board_Game,
    LABEL_Card_Game,
    LABEL_Mini_Game,
    LABEL_Party_Game,
    LABEL_Defence,
    LABEL_Driving,
    LABEL_Hangout,
    LABEL_Hide_And_Seek,
    LABEL_Prop_Hunt,
    LABEL_Music_Gallery,
    LABEL_Costume_Gallery,
    LABEL_Sticker_Gallery,
    LABEL_Movie,
    LABEL_Pinball,
    LABEL_Technology,
    LABEL_Homage,
    LABEL_8_Bit,
    LABEL_16_Bit,
    LABEL_Seasonal,
    LABEL_Time_Trial,
    LABEL_INTERACTIVE_STREAM,
    LABEL_QUESTS,
    LABEL_SACKPOCKET,
    LABEL_SPRINGINATOR,
    LABEL_HOVERBOARD_NAME,
    LABEL_FLOATY_FLUID_NAME,
    LABEL_ODDSOCK,
    LABEL_TOGGLE,
    LABEL_SWOOP,
    LABEL_SACKBOY,
    LABEL_CREATED_CHARACTERS,
}