using System.Diagnostics.CodeAnalysis;

namespace LBPUnion.ProjectLighthouse.Types.Levels;

/// <summary>
///     A series of tags that can be applied to a level
///     Only used in LBP1
/// </summary>
[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
public enum LevelTags
{
    Brilliant,
    Beautiful,
    Funky,
    Points_Fest,
    Weird,
    Tricky,
    Short,
    Vehicles,
    Easy,
    Cute,
    Quick,
    Fun,
    Relaxing,
    Great,
    Speedy,
    Race,
    Multi_Path,
    Machines,
    Complex,
    Pretty,
    Rubbish,
    Toys,
    Repetitive,
    Machinery,
    Satisfying,
    Braaains,
    Fast,
    Simple,
    Long,
    Slow,
    Mad,
    Hectic,
    Creepy,
    Perilous,
    Empty,
    Ingenious,
    Lousy,
    Frustrating,
    Timing,
    Boss,
    Springy,
    Funny,
    Musical,
    Good,
    Hilarious,
    Electric,
    Puzzler,
    Platformer,
    Difficult,
    Mechanical,
    Horizontal,
    Splendid,
    Fiery,
    Swingy,
    Single_Path,
    Annoying,
    Co_op,
    Boring,
    Moody,
    Bubbly,
    Nerve_wracking,
    Hoists,
    Ugly,
    Daft,
    Ramps,
    Secrets,
    Floaty,
    Artistic,
    Competitive,
    Gas,
    Varied,
    Stickers,
    Spikes,
    Collectables,
    Vertical,
    Balancing,
}