blank_issues_enabled: true
contact_links:
  - name: Feature Request/Idea
    url: https://github.com/LBPUnion/ProjectLighthouse/discussions/new?category=ideas
    about: Ideas and feature requests are kept in GitHub Discussions.
