on:
  schedule:
  - cron: "*/60 * * * *"

name: Download Translations from Crowdin

jobs:
  crowdin-sync:
    if: github.repository_owner == 'LBPUnion'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: crowdin-action
        uses: crowdin/github-action@v1.9.0
        with:
          upload_translations: false
          download_translations: true
          export_only_approved: true
          push_translations: true
          commit_message: '[skip ci] Update the localization files'
          localization_branch_name: translations
          create_pull_request: true
          pull_request_title: 'Update the localization files'
          pull_request_body: 'These are the newest translations from [Crowdin](https://crowdin.com/project/lbp-union-project-lighthouse).'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
