on:
  push:
    branches: [main]

name: Upload Translations to Crowdin

jobs:
  crowdin-sync:
    if: github.repository_owner == 'LBPUnion'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: crowdin-action
        uses: crowdin/github-action@v1.9.0
        with:
          upload_translations: true
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
